version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
      # - "5678:5678"  # debugpy port (uncomment for debugging)
    environment:
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}
    volumes:
      - ./:/app
      - ./frontend:/app/frontend
    # Normal mode (comment this line and uncomment debug mode to debug)
    # command: uvicorn main_frontend_bridge:app --host 0.0.0.0 --port 8000 --reload
    # Debug mode (uncomment to enable debugging)
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge